name: Build and Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * 0" # Rebuild the image once a week

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      id-token: write
      
    steps:
    - name: Login to Docker Hub
      uses: grafana/shared-workflows/actions/dockerhub-login@ef3a62a3ca4c1a15505b4235a5a51493194da3c7 # dockerhub-login/v1.0.4
      if: github.event_name != 'pull_request'
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
          persist-credentials: false
    - run: make build
    - run: make push
      if: github.event_name != 'pull_request'
