name: Build and Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * 0" # Rebuild the image once a week

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      id-token: write
      
    steps:
    - uses: grafana/shared-workflows/actions/login-to-gar@1f541877ceb22c7be7667d8a8df04984aeac9f9d # login-to-gar/v1.0.3
      if: github.event_name != 'pull_request'
      id: login-to-gar

    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      with:
          persist-credentials: false

    - run: make build

    - run: make push
      if: github.event_name != 'pull_request'
